app: web
debug: true
db:
  web:
    dialect: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/web?charset=utf8mb4&parseTime=True&loc=Local
redis:
  clients:
    web:
      addrs:
        - 127.0.0.1:6379
      db: 0
      password:
      type: single-node
  default: default
log:
  outputs:
    - stdout
    - ./logs/api.log
